# Generated by Django 3.2.25 on 2025-04-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20250418_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='car',
            name='description',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price',
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=100),
        ),
    ]
